# Generated by Django 5.2.4 on 2025-09-26 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('statutR', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('role', models.CharField(choices=[('client', 'Client'), ('proprietaire', 'Propriétaire'), ('veyra', 'Vérificateur')], default='client', max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datePaiement', models.DateTimeField(auto_now_add=True)),
                ('moyenPaiement', models.CharField(choices=[('Carte', 'Carte bancaire'), ('PayPal', 'PayPal'), ('MobileMoney', 'Mobile Money')], max_length=20)),
                ('statutP', models.CharField(choices=[('effectue', 'Effectué'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='effectue', max_length=20)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='voiture.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='voiture.utilisateur'),
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.PositiveIntegerField()),
                ('couleur', models.CharField(max_length=30)),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('transmission', models.CharField(choices=[('automatique', 'Automatique'), ('manuelle', 'Manuelle')], default='manuelle', max_length=20)),
                ('nb_places', models.IntegerField()),
                ('prix_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilite', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='voitures/')),
                ('description', models.TextField(blank=True, null=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voitures', to='voiture.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='voiture.voiture'),
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('dateAvis', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='voiture.utilisateur')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='voiture.voiture')),
            ],
        ),
    ]
