# Generated by Django 5.2.6 on 2025-09-29 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
