# Generated by Django 5.2.6 on 2025-09-30 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0002_alter_reservation_options_reservation_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
