# Generated by Django 5.2.6 on 2025-10-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0003_alter_utilisateur_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
