# Generated by Django 5.2.6 on 2025-10-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0004_utilisateur_is_2fa_enabled_utilisateur_otp_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='is_2fa_enabled',
            new_name='email_verified',
        ),
    ]
