# Generated by Django 5.2.6 on 2025-10-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0005_rename_is_2fa_enabled_utilisateur_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statutR',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
